memory:
  controller:
    activation_count_dump_file: activate_dump.txt
    addr_mapper:
      mapping: MOP4CLXOR
      type: Linear
    cmd_trace_prefix: TEST
    otherq_max: 30000
    print_cmd_trace: false
    record_cmd_trace: false
    refresh:
      type: Generic
    row_policy:
      type: Opened
    scheduler:
      cap: 16
      type: FRFCFS_CAP
    track_activation_count: false
  period: 0.625
  spec:
    org:
      Ch: 1
      Ra: 2
      preset: DDR4_8Gb_x8
    power:
      IDD0: 60
      IDD2N: 50
      IDD3N: 55
      IDD4R: 145
      IDD4W: 145
      IDD5B: 362
      IPP0: 3
      IPP2N: 3
      IPP3N: 3
      IPP4R: 3
      IPP4W: 3
      IPP5B: 48
      VDD: 1.2
      VPP: 2.5
    speed:
      preset: DDR4_3200W
      refresh: 1X
  standard: DDR4
  tick: 2
  translation:
    hydra: Unfortunately
    type: LessRandom
post_warmup_settings:
  memory:
    controller:
      refresh_based_defense:
        activation_threshold: 250
        aggressor_cache_size: 128
        conservative: true
        debug: false
        debug_base: false
        debug_verbose: false
        no_counters_per_hash: 512
        no_hashes: 4
        probability_threshold: 0.158
        reset_period: 64000000
        rowhammer_threshold: 500
        type: CoMeT
      track_activation_count: false
processor:
  cache:
    L3:
      capacity: 8MB
      latency: 31
  depth: 128
  early_exit: true
  expected_limit_insts: 200000000
  ipc: 4
  tick: 5
  trace:
  - ./cputraces/429.mcf
  warmup_insts: 100000000
stats:
  prefix: ddr4
  suffix: stats
version: 1.0
